// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkManagmentAPI.Data;

#nullable disable

namespace NetworkManagmentAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231222123712_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetworkManagementAPI.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AddressType")
                        .HasColumnType("int");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressName = "Rustaveli 5",
                            AddressType = 1,
                            DistributorId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressName = "Rustaveli 6",
                            AddressType = 2,
                            DistributorId = 1
                        },
                        new
                        {
                            Id = 3,
                            AddressName = "Pekini 21",
                            AddressType = 1,
                            DistributorId = 2
                        },
                        new
                        {
                            Id = 4,
                            AddressName = "Kostava 13",
                            AddressType = 1,
                            DistributorId = 3
                        },
                        new
                        {
                            Id = 5,
                            AddressName = "Tsereteli 5",
                            AddressType = 2,
                            DistributorId = 3
                        });
                });

            modelBuilder.Entity("NetworkManagementAPI.Entities.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "555338877",
                            ContactType = 1,
                            DistributorId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "giorgigiorgadze@gmail.com",
                            ContactType = 3,
                            DistributorId = 1
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "davit123@gmail.com",
                            ContactType = 3,
                            DistributorId = 2
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "551448877",
                            ContactType = 2,
                            DistributorId = 2
                        },
                        new
                        {
                            Id = 5,
                            ContactNumber = "558776932",
                            ContactType = 2,
                            DistributorId = 3
                        },
                        new
                        {
                            Id = 6,
                            ContactNumber = "anano@yahoo.com",
                            ContactType = 3,
                            DistributorId = 3
                        },
                        new
                        {
                            Id = 7,
                            ContactNumber = "123879",
                            ContactType = 4,
                            DistributorId = 3
                        });
                });

            modelBuilder.Entity("NetworkManagementAPI.Entities.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RecomendationsCount")
                        .HasColumnType("int");

                    b.Property<int>("RecomendatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Distributors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1995, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Giorgi",
                            Gender = 1,
                            LastName = "Giorgadze",
                            RecomendationsCount = 0,
                            RecomendatorId = 0
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2000, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Davit",
                            Gender = 1,
                            LastName = "Davitidze",
                            RecomendationsCount = 0,
                            RecomendatorId = 0
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anano",
                            Gender = 2,
                            LastName = "Ananiashvili",
                            RecomendationsCount = 0,
                            RecomendatorId = 0
                        });
                });

            modelBuilder.Entity("NetworkManagementAPI.Entities.PersonalIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DocumentSeries")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("Date");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.ToTable("PersonalIdentifiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistributorId = 1,
                            DocumentNumber = "123",
                            DocumentSeries = "12345678",
                            DocumentType = 1,
                            ExpireDate = new DateTime(2021, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuingAuthority = "Justice house",
                            PersonalNumber = "0102487452",
                            ReleaseDate = new DateTime(2016, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DistributorId = 1,
                            DocumentNumber = "332",
                            DocumentSeries = "115632",
                            DocumentType = 2,
                            ExpireDate = new DateTime(2015, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuingAuthority = "Justice house",
                            PersonalNumber = "012589632",
                            ReleaseDate = new DateTime(2010, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DistributorId = 2,
                            DocumentNumber = "125",
                            DocumentSeries = "115633",
                            DocumentType = 1,
                            ExpireDate = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuingAuthority = "Justice house",
                            PersonalNumber = "41587463983",
                            ReleaseDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DistributorId = 3,
                            DocumentNumber = "658",
                            DocumentSeries = "215633",
                            DocumentType = 2,
                            ExpireDate = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuingAuthority = "Justice house",
                            PersonalNumber = "158965822",
                            ReleaseDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NetworkManagementAPI.Entities.Address", b =>
                {
                    b.HasOne("NetworkManagementAPI.Entities.Distributor", "Distributor")
                        .WithMany("Addresses")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("NetworkManagementAPI.Entities.ContactInfo", b =>
                {
                    b.HasOne("NetworkManagementAPI.Entities.Distributor", "Distributor")
                        .WithMany("ContactInfos")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("NetworkManagementAPI.Entities.PersonalIdentifier", b =>
                {
                    b.HasOne("NetworkManagementAPI.Entities.Distributor", "Distributor")
                        .WithMany("PersonalIdentifiers")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("NetworkManagementAPI.Entities.Distributor", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ContactInfos");

                    b.Navigation("PersonalIdentifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
